version: '3.8'
services:
  kafka-1:
      image: debezium/kafka:2.4
      container_name: cdc-demo-kafka-1
      ports:
          - 9092:9092
      environment:
          - CLUSTER_ID=ZGRkZDM1YTA1MzQwNGQyYT
          - BROKER_ID=1
          - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9092,2@kafka-2:9093,3@kafka-3:9094
          - KAFKA_LISTENERS=INTERNAL://:29092,EXTERNAL://:39092,CONTROLLER://kafka-1:9092
          - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka-1:29092,EXTERNAL://localhost:39092
          - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
          - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL

  kafka-2:
      image: debezium/kafka:2.4
      container_name: cdc-demo-kafka-2
      ports:
          - 9093:9093
      environment:
          - CLUSTER_ID=ZGRkZDM1YTA1MzQwNGQyYT
          - BROKER_ID=2
          - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9092,2@kafka-2:9093,3@kafka-3:9094
          - KAFKA_LISTENERS=INTERNAL://:29093,EXTERNAL://:39093,CONTROLLER://kafka-2:9093
          - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka-2:29093,EXTERNAL://localhost:39093
          - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
          - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL

  kafka-3:
      image: debezium/kafka:2.4
      container_name: cdc-demo-kafka-3
      ports:
          - 9094:9094
      environment:
          - CLUSTER_ID=ZGRkZDM1YTA1MzQwNGQyYT
          - BROKER_ID=3
          - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9092,2@kafka-2:9093,3@kafka-3:9094
          - KAFKA_LISTENERS=INTERNAL://:29094,EXTERNAL://:39094,CONTROLLER://kafka-3:9094
          - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka-3:29094,EXTERNAL://localhost:39094
          - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
          - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL

  postgres:
    image: postgres:latest
    container_name: cdc-demo-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

  schema-registry:
    image: confluentinc/cp-schema-registry:7.5.3
    container_name: cdc-demo-schema-registry
    environment:
        SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: cdc-demo-kafka-1:29092,cdc-demo-kafka-2:29093,cdc-demo-kafka-3:29094
        SCHEMA_REGISTRY_HOST_NAME: cdc-demo-schema-registry
        SCHEMA_REGISTRY_LISTENERS: http://cdc-demo-schema-registry:8080,http://localhost:8080
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    ports:
      - "8080:8080"

  connect:
    image: debezium/connect:latest
    container_name: cdc-demo-debezium
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
      - postgres
      - schema-registry
    environment:
      BOOTSTRAP_SERVERS: cdc-demo-kafka-1:29092,cdc-demo-kafka-2:29093,cdc-demo-kafka-3:29094
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: debezium_config
      OFFSET_STORAGE_TOPIC: debezium_offset
      STATUS_STORAGE_TOPIC: debezium_status
      CONNECT_REST_ADVERTISED_HOST_NAME: connect
      CONNECT_PLUGIN_PATH: /kafka/connect
      CONNECT_DEBEZIUM_POSTGRES_SNAPSHOT_MODE: initial
      POSTGRES_DATABASE: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "8083:8083"
    volumes:
      - ./confluentinc-kafka-connect-avro-converter-7.7.0/lib:/kafka/connect/libs

volumes:
  postgres_data:

